ip - show ip of a bosh-lite

diff --git a/scaffold/bin/boss-lite b/scaffold/bin/boss-lite
--- a/scaffold/bin/boss-lite
+++ b/scaffold/bin/boss-lite
@@ -121,10 +121,10 @@ target() {
     exit 1
   fi
   shift
-  path=${base_path}/${name}
+  path=${ROOT}/${base_path}/${name}
   cd ${path}
 
-  IP=$(vagrant ssh-config | grep HostName | awk '{print $2}')
+  IP=$(ip $name)
   set -x
   bosh target ${IP} ${name}
 }
@@ -140,6 +140,25 @@ dir() {
   shift
   path=${ROOT}/${base_path}/${name}
   echo $path
+}
+
+ip() {
+  checkenv
+  name=$1
+  if [[ "${name}X" == "X" ]]; then
+    echo "USAGE: boss-lite cd NAME"
+    exit 1
+  fi
+  shift
+  path=${ROOT}/${base_path}/${name}
+  cd ${path}
+
+  if [[ ! -f ip ]]; then
+    # some old deployments might be missing 'ip' file
+    IP=$(vagrant ssh-config | grep HostName | awk '{print $2}')
+    echo ${IP} > ip
+  fi
+  cat ip
 }
 
 ssh() {
@@ -188,9 +207,9 @@ update() {
   git commit -a -m "update boss-lite CLI"
 }
 
-if [[ $1 =~ ^(new|target|dir|list|status|deployments|ssh|destroy|update|checkenv)$ ]]; then
+if [[ $1 =~ ^(new|target|ip|dir|list|status|deployments|ssh|destroy|update|checkenv)$ ]]; then
   "$@"
 else
-  echo "Invalid subcommand: $1 - available: new, target, dir, list, status, ssh, destroy, update" >&2
+  echo "Invalid subcommand: $1 - available: new, target, ip, dir, list, status, ssh, destroy, update" >&2
   exit 1
 fi
