ssh command - ssh into a bosh-lite vm

diff --git a/scaffold/bin/boss-lite b/scaffold/bin/boss-lite
--- a/scaffold/bin/boss-lite
+++ b/scaffold/bin/boss-lite
@@ -48,6 +48,19 @@ new() {
   bosh -t ${name} upload stemcell https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent
 }
 
+ssh() {
+  checkenv
+  name=$1
+  if [[ "${name}X" == "X" ]]; then
+    echo "USAGE: boss-lite ssh NAME"
+    exit 1
+  fi
+  shift
+  path=${base_path}/${name}
+  cd ${path}
+  vagrant ssh
+}
+
 destroy() {
   name=$1
   if [[ "${name}X" == "X" ]]; then
@@ -73,9 +86,9 @@ update() {
     -m "Update bosh-lite scripts"
 }
 
-if [[ $1 =~ ^(new|destroy|update|checkenv)$ ]]; then
+if [[ $1 =~ ^(new|ssh|destroy|update|checkenv)$ ]]; then
   "$@"
 else
-  echo "Invalid subcommand: $1 - available: new, destroy, update" >&2
+  echo "Invalid subcommand: $1 - available: new, ssh, destroy, update" >&2
   exit 1
 fi
